In [48]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score


In [3]:
df=pd.read_csv('iris.csv')
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [5]:
df.shape

(150, 5)

In [7]:
X=df.drop(columns=['species'])
Y=df['species']

##**Train the KNeighborClassifier model**

In [8]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=41, test_size=0.2)

In [43]:
k=KNeighborsClassifier(n_neighbors=5)
k.fit(x_train,y_train)
y_pred=k.predict(x_test)

confusion_matrix(y_test,y_pred)

array([[ 9,  0,  0],
       [ 0, 10,  1],
       [ 0,  0, 10]])

In [55]:
def KN(n):
  a=[]
  f=[]
  p=[]
  for i in range(n):
    k=KNeighborsClassifier(n_neighbors=5)
    k.fit(x_train,y_train)
    y_pred=k.predict(x_test)

    a.append(round(accuracy_score(y_test,y_pred),2)*100)
    f.append(round(recall_score(y_test,y_pred, average='macro'),2)*100)
    p.append(round(precision_score(y_test,y_pred, average='macro'),2)*100)

  print('Accuracy Score:',max(a))
  print('F1_score:',max(f))
  print('Precision_score:',max(p))
  print('Confusion Matrix:\n',confusion_matrix(y_test,y_pred))

KN(10)

Accuracy Score: 97.0
F1_score: 97.0
Precision_score: 97.0
Confusion Matrix:
 [[ 9  0  0]
 [ 0 10  1]
 [ 0  0 10]]
